title: 5е українською
tagline: 'Довідник з правил 5e'
description: 'Переклад System Reference Document на основі Open Game License v.1.0a'
locale: uk_UA
google_analytics_id: G-3YDX4S83WP
timezone: Europe/Kiev

exclude:
  - work

# Collections
collections_dir: srd
collections:
  docs:
    output: true
  items:
    output: true
  monsters:
    output: true
  spells:
    output: true

# Social links
twitter_username: 
github_username:  tuomari-ua
stackoverflow_username: 
dribbble_username: 
facebook_username: 
flickr_username: 
instagram_username: 
linkedin_username: 
xing_username: 
pinterest_username: 
youtube_username: 
orcid_username: 
googlescholar_username:
telegram_username: inrium
discord_username: nQVxdUsGrH
