title: 5е українською
description: Переклад System Reference Document на основі Open Game License v.1.0a
locale: uk_UA
google_analytics_id: G-3YDX4S83WP
timezone: Europe/Kiev

# Collections
collections_dir: srd
collections:
  docs:
    output: true
  items:
    output: true
  monsters:
    output: true
  spells:
    output: true
